# Generated by Django 3.1 on 2020-08-08 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='until_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
