# Generated by Django 3.1 on 2020-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=15),
        ),
    ]
